title: Yasmina Elmore
description: Aerospace Engineer

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

baseurl: ""

google_analytics: 

description:

collections:
  projects:
    output: true
    permalink: /projects/:title/
