title: Yasmina Elmore
description: Aerospace Engineer

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme

baseurl: ""

google_analytics: 

description:

collections:
  projects_mechanical_design:
    output: true
    permalink: /projects_mechanical_design/:title/
  projects_fluid_dynamics:
    output: true
    permalink: /projects_fluid_dynamics/:title/
  projects_computer_science:
    output: true
    permalink: /projects_computer_science/:title/
